/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NhsxQuestionnaire {
    'questionnaire': any;
    'sections': Array<string>;
  }
  interface NhsxQuestionnaireAttributes extends StencilHTMLAttributes {
    'questionnaire'?: any;
    'sections'?: Array<string>;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NhsxQuestionnaire': Components.NhsxQuestionnaire;
  }

  interface StencilIntrinsicElements {
    'nhsx-questionnaire': Components.NhsxQuestionnaireAttributes;
  }


  interface HTMLNhsxQuestionnaireElement extends Components.NhsxQuestionnaire, HTMLStencilElement {}
  var HTMLNhsxQuestionnaireElement: {
    prototype: HTMLNhsxQuestionnaireElement;
    new (): HTMLNhsxQuestionnaireElement;
  };

  interface HTMLElementTagNameMap {
    'nhsx-questionnaire': HTMLNhsxQuestionnaireElement
  }

  interface ElementTagNameMap {
    'nhsx-questionnaire': HTMLNhsxQuestionnaireElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
